// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChatClubAPI.Data;

public partial class Account
{
    public Guid UserId { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string Name { get; set; }

    public int Gender { get; set; }

    public int Role { get; set; }

    public DateTime CreateDate { get; set; }

    public bool Active { get; set; }

    public virtual ICollection<Location> Locations { get; set; } = new List<Location>();

    public virtual ICollection<UserLocation> UserLocations { get; set; } = new List<UserLocation>();

    public virtual ICollection<UserToken> UserTokens { get; set; } = new List<UserToken>();
}