// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChatClubAPI.Data;

public partial class Location
{
    public int LocationId { get; set; }

    public string Name { get; set; }

    public string Latitude { get; set; }

    public string Longtitude { get; set; }

    public Guid OwnerId { get; set; }

    public bool Active { get; set; }

    public virtual Account Owner { get; set; }
}