// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChatClubAPI.Data;

public partial class UserToken
{
    public int Id { get; set; }

    public Guid AccountId { get; set; }

    public string AccessToken { get; set; }

    public string RefreshToken { get; set; }

    public DateTime CreateAt { get; set; }

    public virtual Account User { get; set; }
}