// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChatClubAPI.Data;

public partial class UserInterest
{
    public long Id { get; set; }

    public Guid AccountId { get; set; }

    public string Description { get; set; }

    public virtual Account Account { get; set; }
}