// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChatClubAPI.Data;

public partial class UserLocation
{
    public long Id { get; set; }

    public Guid UserId { get; set; }

    public string Latitude { get; set; }

    public string Longtitude { get; set; }

    public string LocationName { get; set; }

    public DateTime Timestamp { get; set; }

    public int Event { get; set; }

    public virtual Account User { get; set; }
}