// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChatClubAPI.Data;

public partial class UserProfile
{
    public int Id { get; set; }

    public Guid AccountId { get; set; }

    public int? Age { get; set; }

    public string AboutMe { get; set; }

    public string AvatarUrl { get; set; }

    public virtual Account Account { get; set; }
}